In [6]:
#import numpy 
import numpy as np

In [21]:
#creation array 
array = np.array([1,2,"three",4,5])
print(array)
#avec random values 
arandom = np.random.rand(2, 4)
print(arandom)
#avec range (start, stop, step)
arrange = np.array(range(0,30,3))
print(arrange)
#avec que des zeros 
zeros = np.zeros((2,3))
print(zeros)
#que du un
ones = np.ones((2,3))
print(ones)
#meme valeur 
mv = np.full((2,2), 3)
print(mv)

['1' '2' 'three' '4' '5']
[[0.26035379 0.45887411 0.50851919 0.56066324]
 [0.36255562 0.15018622 0.5495567  0.75246338]]
[ 0  3  6  9 12 15 18 21 24 27]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]]
